Parameters:
  GithubOrg:
    Type: String
    Default: yourorg
  RepoName:
    Type: String
    Default: yourrepo

Resources:
  GitHubBootstrapRole:
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: F3
            reason: "Need *"
          - id: W28
            reason: "Static Role"
    Type: AWS::IAM::Role
    Properties:
      RoleName: Github-Bootstrap
      MaxSessionDuration: 3600
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: "AllowGitHub"
            Effect: Allow
            Action: sts:AssumeRoleWithWebIdentity
            Principal:
              Federated: !Ref GithubOIDC
            Condition:
              StringLike:
                token.actions.githubusercontent.com:sub: !Sub repo:${GithubOrg}/${RepoName}:*
      Policies:
        - PolicyName: "allowassume"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: AssumeAccoount
                Effect: Allow
                Action: ["sts:AssumeRole"]
                Resource: "arn:aws:iam::*:role/Github-Admin"
        - PolicyName: "DeployCFN"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: CFNDeploy
                Effect: Allow
                Action: "cloudformation:*"
                Resource: 
                  - "*"
              - Sid: DenyCFNDelete
                Effect: Deny
                Action: "cloudformation:Delete*"
                Resource: 
                  - "*"
        - PolicyName: "GetRole"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: RoleASSUME
                Effect: Allow
                Action:
                  - "iam:AttachRolePolicy"
                  - "iam:CreateRole"
                  - "iam:DeleteRole"
                  - "iam:DeleteRolePolicy"
                  - "iam:DetachRolePolicy"
                  - "iam:GetRole"
                  - "iam:PassRole"
                  - "iam:PutRolePolicy"
                  - "iam:getRolePolicy"
                  - "iam:Tag*"
                Resource: "arn:aws:iam::*:role/Bedrock-*"
        - PolicyName: "LambdaCreate"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: LambdaCreates
                Effect: Allow
                Action:
                  - "lambda:CreateFunction"
                  - "lambda:DeleteFunction"
                  - "lambda:GetFunction"
                  - "lambda:InvokeFunction"
                  - "lambda:UpdateFunction*"
                Resource: "arn:aws:lambda:*:*:function:bedrock-*"
        - PolicyName: "LogGroupCreate"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: LogCreate
                Effect: Allow
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:DeleteLogGroup"
                  - "logs:PutRetentionPolicy"
                Resource: "arn:aws:logs:*:*:log-group:/aws/lambda/*"

  GithubOIDC:
    Type: AWS::IAM::OIDCProvider
    Properties:
      Url: https://token.actions.githubusercontent.com
      ThumbprintList: 
        - 6938fd4d98bab03faadb97b34396831e3780aea1
      ClientIdList:
        - sts.amazonaws.com

Outputs:
  GitHubBootstrap:
    Value: !GetAtt GitHubBootstrapRole.Arn
