Parameters:
  GitlabOrg:
    Type: String
    Default: yourorg
  RepoName:
    Type: String
    Default: yourrepo

Resources:
  GitLabBootstrapRole:
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: F3
            reason: "Need *"
          - id: W28
            reason: "Static Role"
    Type: AWS::IAM::Role
    Properties:
      RoleName: GitLab-Bootstrap
      MaxSessionDuration: 3600
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: "AllowGitLab"
            Effect: Allow
            Action: sts:AssumeRoleWithWebIdentity
            Principal:
              Federated: !Ref GitLabOIDC
            Condition:
              StringLike:
                gitlab.com:sub: !Sub project_path:${GitlabOrg}/${RepoName}:*
      Policies:
        - PolicyName: "allowassume"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: AssumeAccoount
                Effect: Allow
                Action: ["sts:AssumeRole"]
                Resource: "arn:aws:iam::*:role/GitLab-Admin"
        - PolicyName: "DeployCFN"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: CFNDeploy
                Effect: Allow
                Action: "cloudformation:*"
                Resource: 
                  - "*"
              - Sid: DenyCFNDelete
                Effect: Deny
                Action: "cloudformation:Delete*"
                Resource: 
                  - "*"
        - PolicyName: "GetRole"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: RoleASSUME
                Effect: Allow
                Action:
                  - "iam:AttachRolePolicy"
                  - "iam:CreateRole"
                  - "iam:DeleteRole"
                  - "iam:DeleteRolePolicy"
                  - "iam:DetachRolePolicy"
                  - "iam:GetRole"
                  - "iam:PassRole"
                  - "iam:PutRolePolicy"
                  - "iam:getRolePolicy"
                  - "iam:Tag*"
                Resource: "arn:aws:iam::*:role/Bedrock-*"
        - PolicyName: "LambdaCreate"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: LambdaCreates
                Effect: Allow
                Action:
                  - "lambda:CreateFunction"
                  - "lambda:DeleteFunction"
                  - "lambda:GetFunction"
                  - "lambda:InvokeFunction"
                  - "lambda:UpdateFunction*"
                Resource: "arn:aws:lambda:*:*:function:bedrock-*"
        - PolicyName: "LogGroupCreate"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: LogCreate
                Effect: Allow
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:DeleteLogGroup"
                  - "logs:PutRetentionPolicy"
                Resource: "arn:aws:logs:*:*:log-group:/aws/lambda/*"

  GitLabOIDC:
    Type: AWS::IAM::OIDCProvider
    Properties:
      Url: https://gitlab.com
      ThumbprintList: 
        - d89e3bd43d5d909b47a18977aa9d5ce36cee184c
      ClientIdList:
        - https://gitlab.com

Outputs:
  GitLabBootstrap:
    Value: !GetAtt GitLabBootstrapRole.Arn
