stages:
  - aws_creds
  - terraform_plan
  - terraform_apply

# Need AWS credentials and correct role setup for further jobs
aws_account:
  stage: aws_creds
  before_script:
    - cd tf/${ENVIRONMENT}
  script:
    - ../deploy/aws_assumerole.sh
  artifacts:
    reports:
      dotenv: tf/${ENVIRONMENT}/credentials.env

terraform_plan:
  stage: terraform_plan
  needs:
    - job: aws_account
      artifacts: true
  before_script:
    - cd tf/${ENVIRONMENT}
  cache:
    key: terraform
    paths:
      - tf/${ENVIRONMENT}/.terraform
  script:
    - ../deploy/tf_state.sh
    - ../deploy/tf_plan.sh
  artifacts:
    paths:
      - tf/${ENVIRONMENT}/plan

# Only main branch will apply the IaC
terraform_apply:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  stage: terraform_apply
  needs:
    - job: aws_account
      artifacts: true
  before_script:
    - cd tf/${ENVIRONMENT}
  cache:
    key: terraform
    paths:
      - tf/${ENVIRONMENT}/.terraform
  script:
      - ../deploy/tf_state.sh
      - ../deploy/tf_deploy.sh

